modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL="https://github.com/{{github_owner}}/{{github_repo}}/issues"

[[mods]]
modId = "{{mod_id}}"
version = "${file.jarVersion}"
displayName = "{{name}}"
displayURL="https://github.com/{{github_owner}}/{{github_repo}}"
logoFile = "icon.png"
authors = "{{author}}"
description = '''
{{description}}
'''

[[dependencies.{{mod_id}}]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.{{mod_id}}]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.{{mod_id}}]]
modId = "architectury"
type = "required"
versionRange = "[11.0.9,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.{{mod_id}}]]
modId = "jamlib"
type = "required"
versionRange = "[1.0.3+1.20.4,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "{{mod_id}}.mixins.json"
