modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL="https://github.com/{{github_owner}}/{{github_repo}}/issues"

[[mods]]
modId = "{{mod_id}}"
version = "${file.jarVersion}"
displayName = "{{name}}"
displayURL="https://github.com/{{github_owner}}/{{github_repo}}"
logoFile = "icon.png"
authors = "{{author}}"
description = '''
{{description}}
'''

[[dependencies.{{mod_id}}]]
modId = "neoforge"
mandatory = true
versionRange = "[20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.{{mod_id}}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.{{mod_id}}]]
modId = "architectury"
mandatory = true
versionRange = "[10.0.17,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.{{mod_id}}]]
modId = "jamlib"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "{{mod_id}}.mixins.json"
