name: Test Template Mod Compiles

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: "ubuntu-20.04"

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: "canary"

      - name: Initialize template
        run: deno run --allow-read --allow-write https://raw.githubusercontent.com/Jamalam360/easytemplate/main/easytemplate.ts --disable-interactive-mode --input name="Template Mod Test Mod" --input mod_id=template_mod_test --input description="This is a mod to test the template mod." --input author=Jamalam360 --input group="io.github.jamalam360" --input main_class="TemplateModTest" --input github_owner="JamCoreModding" --input github_repo="multi-loader-template-mod" --input github_publish=true --input unified_publishing=true

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build
        run: ./gradlew clean forge:build neoforge:build fabric:build quilt:build

      - name: Capture Fabric Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Fabric Artifacts
          path: fabric/build/libs/

      - name: Capture Quilt Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Quilt Artifacts
          path: quilt/build/libs/

      - name: Capture Forge Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Forge Artifacts
          path: forge/build/libs/

      - name: Capture NeoForge Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: NeoForge Artifacts
          path: neoforge/build/libs/
      
      - name: Agree to EULAs
        run: touch fabric/run/eula.txt && touch neoforge/run/eula.txt && echo "eula=true" > fabric/run/eula.txt && echo "eula=true" > neoforge/run/eula.txt
      
      - name: Run Test Server (Fabric)
        run: timeout 1m ./gradlew fabric:runServer

      - name: Run Test Server (NeoForge)
        run: timeout 1m ./gradlew neoforge:runServer
